using System.Globalization;
using System.Text;
using NorthLife.Api.Analytics;
using NorthLife.Api.Data;
using NorthLife.Api.Models;
using NorthLife.Api.Ranking;

namespace NorthLife.Api.Recommendations;

public sealed record EvaluationRow(
    string Method,
    double PrecisionAt5,
    double RecallAt5,
    double NdcgAt5,
    double PrecisionAt10,
    double RecallAt10,
    double NdcgAt10,
    double HitRateAt10,
    double Coverage,
    double Diversity);

public sealed record EvaluationReport(
    int Events,
    int Personas,
    int TestUsers,
    int TrainInteractions,
    int TestInteractions,
    int TestSeed,
    int ValidationSeed,
    double Gamma,
    double Mu,
    double Prior,
    IReadOnlyList<OfflineEvaluation.TuningPoint> Grid,
    IReadOnlyList<EvaluationRow> Rows,
    int ColdStartUsers,
    IReadOnlyList<EvaluationRow> ColdStartRows)
{
    public string ToMarkdown()
    {
        var text = new StringBuilder();
        text.AppendLine("# Recommendation offline evaluation");
        text.AppendLine();
        text.AppendLine("Generated by `dotnet NorthLife.Api.dll --evaluate-recommendations`.");
        text.AppendLine();
        text.AppendLine("Real traffic is too small to evaluate on, so the evaluation uses the persona simulator (see docs/features/recommendations.md). Simulated visitors with known tastes browse the catalogue for 30 days. The models are trained on the first 24 days and must predict which events each visitor opens in the last 6.");
        text.AppendLine();
        text.AppendLine("## Setup");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"- Catalogue: {Events} events.");
        text.AppendLine(CultureInfo.InvariantCulture, $"- Visitors: {Personas} simulated visitors.");
        text.AppendLine(CultureInfo.InvariantCulture, $"- Interactions: {TrainInteractions:N0} for training, {TestInteractions:N0} for testing.");
        text.AppendLine(CultureInfo.InvariantCulture, $"- Test users: {TestUsers} visitors who have training history and open at least one new event in the test period.");
        text.AppendLine("- Relevant events: those a visitor opened or navigated to in the test period and had not opened before.");
        text.AppendLine("- Averaging: every metric is averaged over visitors.");
        text.AppendLine("- Coverage: the share of the catalogue that appears in anyone's top 10.");
        text.AppendLine("- Diversity: the mean pairwise (1 − content cosine) inside a top-10 list.");
        text.AppendLine();
        text.AppendLine("## Tuning");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"The hyperparameters were tuned on a separate validation seed ({ValidationSeed}) and reported on the test seed ({TestSeed}), so the numbers below were not tuned on the data they report.");
        text.AppendLine();
        text.AppendLine("The grid searched three settings:");
        text.AppendLine();
        text.AppendLine("- γ, the blend constant, with α = γ / (γ + shared visitors).");
        text.AppendLine("- μ, the weight of the popularity prior.");
        text.AppendLine("- The popularity percentile assumed for events nobody has seen yet.");
        text.AppendLine();
        text.AppendLine("Every event starts cold, so the objective values both cases equally:");
        text.AppendLine();
        text.AppendLine("J = NDCG@10 on known events ÷ the oracle's + NDCG@10 on new events ÷ the oracle's.");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"Chosen: **γ = {Gamma}, μ = {Mu}, new-event prior = {Prior}**. The best ten configurations:");
        text.AppendLine();
        text.AppendLine("| γ | μ | prior | NDCG@10 known | NDCG@10 new | J |");
        text.AppendLine("| --- | --- | --- | --- | --- | --- |");
        foreach (var point in Grid.OrderByDescending(point => point.Objective).Take(10))
        {
            text.AppendLine(CultureInfo.InvariantCulture, $"| {point.Gamma} | {point.Mu} | {point.Prior} | {point.WarmNdcg:0.000} | {point.ColdNdcg:0.000} | {point.Objective:0.000} |");
        }

        text.AppendLine();
        text.AppendLine("## Results");
        text.AppendLine();
        text.AppendLine("| Method | P@5 | R@5 | NDCG@5 | P@10 | R@10 | NDCG@10 | Hit@10 | Coverage | Diversity |");
        text.AppendLine("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |");
        foreach (var row in Rows)
        {
            text.AppendLine(CultureInfo.InvariantCulture,
                $"| {row.Method} | {row.PrecisionAt5:0.000} | {row.RecallAt5:0.000} | {row.NdcgAt5:0.000} | {row.PrecisionAt10:0.000} | {row.RecallAt10:0.000} | {row.NdcgAt10:0.000} | {row.HitRateAt10:0.000} | {row.Coverage:0.000} | {row.Diversity:0.000} |");
        }

        text.AppendLine();
        text.AppendLine("## New events (item cold start)");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"A fifth of the catalogue is published only at the split: none of its interactions are in training, so no visitor has shared history with it. Relevant events here are only these new ones. The table covers {ColdStartUsers} visitors who opened at least one.");
        text.AppendLine();
        text.AppendLine("Behaviour-based methods cannot see these events. The blend falls back to text, since with no shared visitors α = 1.");
        text.AppendLine();
        text.AppendLine("| Method | R@10 | NDCG@10 | Hit@10 |");
        text.AppendLine("| --- | --- | --- | --- |");
        foreach (var row in ColdStartRows)
        {
            text.AppendLine(CultureInfo.InvariantCulture, $"| {row.Method} | {row.RecallAt10:0.000} | {row.NdcgAt10:0.000} | {row.HitRateAt10:0.000} |");
        }

        return text.ToString();
    }
}

/// <summary>
/// Offline evaluation with a time split, fully in memory and deterministic for a seed:
/// <list type="bullet">
/// <item>The demo catalogue three times over (different towns, days and prices; 192 events).</item>
/// <item>A month of simulated traffic. Models are fitted on the first 24 days only, and top-10 lists
/// are scored against what each visitor opened in the last 6 days.</item>
/// <item>Hyperparameters (γ, μ) are chosen on a validation seed; everything reported is on another seed.</item>
/// </list>
/// Baselines: random; popularity (decayed engagement at the split); content only (α = 1);
/// collaborative only (α = 0); the blend without the popularity prior, without MMR and with it; and
/// an oracle that ranks by each visitor's true relevance, the ceiling the simulated behaviour allows.
/// </summary>
public static class OfflineEvaluation
{
    public static readonly double[] GammaGrid = [1, 5, 25, 100];
    public static readonly double[] MuGrid = [0, 0.2, 0.4, 0.6, 0.8];
    /// <summary>
    /// From the median to the 90th percentile. A prior of 1 would declare every new event as popular
    /// as the most popular one, which is not optimism under uncertainty but a flood: events are
    /// published every day, and new ones would crowd every list.
    /// </summary>
    public static readonly double[] PriorGrid = [0.5, 0.75, 0.9];
    public const double MmrLambda = 0.8;

    private static readonly DateTimeOffset Reference = new(2026, 10, 1, 9, 0, 0, TimeSpan.Zero);

    public static EvaluationReport Run(int testSeed = 2026, int validationSeed = 7, int personas = 1500)
    {
        var validation = Dataset.Create(validationSeed, personas);
        var validationCold = Dataset.Create(validationSeed, personas, newEventShare: 0.2);
        var warmCeiling = validation.Score("oracle", validation.OracleList).NdcgAt10;
        var coldCeiling = validationCold.Score("oracle", validationCold.OracleList).NdcgAt10;
        var grid = new List<TuningPoint>();
        foreach (var gamma in GammaGrid)
        {
            foreach (var mu in MuGrid)
            {
                foreach (var prior in PriorGrid)
                {
                    var options = new RecommendationOptions { BlendGamma = gamma, PopularityWeight = mu, NewEventPrior = prior, MmrLambda = 1 };
                    var warmNdcg = validation.Score("tuning", validation.Personalised(options)).NdcgAt10;
                    var coldNdcg = validationCold.Score("tuning", validationCold.Personalised(options)).NdcgAt10;
                    grid.Add(new TuningPoint(gamma, mu, prior, warmNdcg, coldNdcg, warmNdcg / warmCeiling + coldNdcg / coldCeiling));
                }
            }
        }

        var best = grid.MaxBy(point => point.Objective)!;
        var test = Dataset.Create(testSeed, personas);
        RecommendationOptions With(double gamma, double mu, double lambda) => new() { BlendGamma = gamma, PopularityWeight = mu, NewEventPrior = best.Prior, MmrLambda = lambda };

        var rows = new List<EvaluationRow>
        {
            test.Score("Random", test.RandomList),
            test.Score("Popularity", test.PopularList),
            test.Score($"Content only (α = 1, μ = {best.Mu})", test.Personalised(With(1e12, best.Mu, 1))),
            test.Score($"Collaborative only (α = 0, μ = {best.Mu})", test.Personalised(With(0, best.Mu, 1))),
            test.Score($"Blend without popularity prior (γ = {best.Gamma}, μ = 0)", test.Personalised(With(best.Gamma, 0, 1))),
            test.Score($"Blend (γ = {best.Gamma}, μ = {best.Mu})", test.Personalised(With(best.Gamma, best.Mu, 1))),
            test.Score($"Blend + MMR (λ = {MmrLambda})", test.Personalised(With(best.Gamma, best.Mu, MmrLambda))),
            test.Score("Oracle (true relevance)", test.OracleList),
        };

        // Item cold start: new events have no training history; can a method still surface them?
        var cold = Dataset.Create(testSeed, personas, newEventShare: 0.2);
        var coldRows = new List<EvaluationRow>
        {
            cold.Score("Popularity", cold.PopularList),
            cold.Score($"Collaborative only (α = 0, μ = {best.Mu})", cold.Personalised(With(0, best.Mu, 1))),
            cold.Score($"Content only (α = 1, μ = {best.Mu})", cold.Personalised(With(1e12, best.Mu, 1))),
            cold.Score($"Blend (γ = {best.Gamma}, μ = {best.Mu})", cold.Personalised(With(best.Gamma, best.Mu, 1))),
            cold.Score($"Blend + MMR (λ = {MmrLambda})", cold.Personalised(With(best.Gamma, best.Mu, MmrLambda))),
            cold.Score("Oracle (true relevance)", cold.OracleList),
        };

        return new EvaluationReport(test.Events.Count, personas, test.Users.Count, test.TrainCount, test.TestCount, testSeed, validationSeed, best.Gamma, best.Mu, best.Prior, grid, rows, cold.Users.Count, coldRows);
    }

    public static double Precision(IReadOnlyList<Guid> list, IReadOnlySet<Guid> relevant, int k) =>
        (double)list.Take(k).Count(relevant.Contains) / k;

    public static double Recall(IReadOnlyList<Guid> list, IReadOnlySet<Guid> relevant, int k) =>
        relevant.Count == 0 ? 0 : (double)list.Take(k).Count(relevant.Contains) / relevant.Count;

    /// <summary>Binary-gain NDCG: DCG = Σ rel_i / log2(i + 1) over the top k, divided by the ideal DCG.</summary>
    public static double Ndcg(IReadOnlyList<Guid> list, IReadOnlySet<Guid> relevant, int k)
    {
        double dcg = 0;
        for (var index = 0; index < Math.Min(k, list.Count); index++)
        {
            if (relevant.Contains(list[index])) dcg += 1 / Math.Log2(index + 2);
        }

        double ideal = 0;
        for (var index = 0; index < Math.Min(k, relevant.Count); index++) ideal += 1 / Math.Log2(index + 2);
        return ideal == 0 ? 0 : dcg / ideal;
    }

    public sealed record TuningPoint(double Gamma, double Mu, double Prior, double WarmNdcg, double ColdNdcg, double Objective);

    private sealed record TestUser(Persona Persona, Dictionary<Guid, double> Profile, HashSet<Guid> Seen, HashSet<Guid> Relevant);

    /// <summary>One simulated month split into training and test, with the models fitted on training.</summary>
    private sealed class Dataset
    {
        private readonly Dictionary<double, Dictionary<Guid, List<Neighbour>>> _neighbours = [];
        private readonly Random _random;

        private Dataset(int seed) => _random = new Random(seed);

        public List<SimulatedEvent> Events { get; } = [];
        public List<Guid> Ids { get; } = [];
        public List<TestUser> Users { get; } = [];
        public int TrainCount { get; private set; }
        public int TestCount { get; private set; }
        private TfIdfModel Content { get; set; } = null!;
        private Dictionary<(Guid, Guid), CoEngagement> Behaviour { get; set; } = [];
        private Dictionary<Guid, double> Popularity { get; set; } = [];
        private List<Guid> PopularOrder { get; set; } = [];
        private HashSet<Guid> Eligible { get; set; } = [];
        private IReadOnlyDictionary<Guid, double> Appeal { get; set; } = new Dictionary<Guid, double>();
        private Dictionary<Guid, SimulatedEvent> ById { get; set; } = [];

        /// <param name="newEventShare">Share of events treated as published at the split: their training
        /// interactions are removed and only they count as relevant.</param>
        public static Dataset Create(int seed, int personas, int trainDays = 24, int testDays = 6, double newEventShare = 0)
        {
            var data = new Dataset(seed);
            var random = new Random(seed);
            var split = Reference.AddDays(-testDays);
            var texts = new List<ItemText>();
            for (var copy = 0; copy < 3; copy++)
            {
                foreach (var spec in DemoCatalog.Events)
                {
                    var id = NewGuid(random);
                    var locality = DemoCatalog.Localities[random.Next(DemoCatalog.Localities.Length)];
                    var price = DemoCatalog.Price(spec.Category, random);
                    var venue = DemoCatalog.Venue(spec.Category, random);
                    texts.Add(new ItemText(id, spec.Title, DemoCatalog.Description(spec, venue, locality, price), spec.Tags, spec.Category, locality.Name));
                    data.Events.Add(new SimulatedEvent(id, spec.Category, (double)locality.Latitude, (double)locality.Longitude, price, split.AddDays(1 + random.Next(20)).AddHours(random.Next(24)), random.NextDouble() < 0.1));
                }
            }

            data.Ids.AddRange(data.Events.Select(item => item.Id));
            data.ById = data.Events.ToDictionary(item => item.Id);
            data.Eligible = data.Ids.ToHashSet();
            var homes = DemoCatalog.Localities.Select(locality => ((double)locality.Latitude, (double)locality.Longitude)).ToList();
            var traffic = SyntheticTraffic.Generate(data.Events, homes, Reference, new SyntheticTrafficOptions { Visitors = personas, Days = trainDays + testDays, Seed = seed, IncludeBursts = false });
            data.Appeal = traffic.Appeal;
            var newEvents = data.Ids.Where(_ => random.NextDouble() < newEventShare).ToHashSet();
            var train = traffic.Interactions.Where(row => row.OccurredAtUtc < split && !newEvents.Contains(row.EventId)).ToList();
            var test = traffic.Interactions.Where(row => row.OccurredAtUtc >= split).ToList();
            data.TrainCount = train.Count;
            data.TestCount = test.Count;

            data.Content = TfIdfModel.Build(texts);
            var visitorItems = train
                .Where(row => row.Type is InteractionType.DetailView or InteractionType.Navigate or InteractionType.Share)
                .GroupBy(row => row.VisitorId)
                .ToDictionary(group => group.Key, group => group.GroupBy(row => row.EventId).ToDictionary(items => items.Key, items => items.Sum(row => EngagementWeight(row.Type))));
            data.Behaviour = Collaborative.ItemSimilarities(visitorItems);

            var weights = PopularityWeights.With(PropensityTable.Uniform);
            var decayed = train
                .GroupBy(row => row.EventId)
                .ToDictionary(group => group.Key, group => DecayedPopularity.ScoreAt(group.Aggregate(double.NegativeInfinity, (sum, row) =>
                    weights(row) > 0 ? DecayedPopularity.LogAddExp(sum, DecayedPopularity.LogContribution(weights(row), row.OccurredAtUtc)) : sum), split));
            data.Popularity = Recommender.ScalePopularity(decayed);
            data.PopularOrder = data.Popularity.OrderByDescending(pair => pair.Value).Select(pair => pair.Key).ToList();

            var personasById = traffic.Personas.ToDictionary(persona => persona.VisitorId);
            var trainByVisitor = train.ToLookup(row => row.VisitorId);
            var options = new RecommendationOptions();
            foreach (var visitor in test.GroupBy(row => row.VisitorId))
            {
                var history = trainByVisitor[visitor.Key].ToList();
                var profile = Recommender.Profile(history, split, options);
                if (profile.Count == 0 || !personasById.TryGetValue(visitor.Key, out var persona)) continue;
                var seen = history.Where(row => row.Type == InteractionType.DetailView).Select(row => row.EventId).ToHashSet();
                var relevant = visitor
                    .Where(row => row.Type is InteractionType.DetailView or InteractionType.Navigate && !seen.Contains(row.EventId))
                    .Where(row => newEventShare == 0 || newEvents.Contains(row.EventId))
                    .Select(row => row.EventId)
                    .ToHashSet();
                if (relevant.Count > 0) data.Users.Add(new TestUser(persona, profile, seen, relevant));
            }

            return data;
        }

        public Func<TestUser, List<Guid>> RandomList => user => Ids.Where(id => !user.Seen.Contains(id)).OrderBy(_ => _random.Next()).Take(10).ToList();

        public Func<TestUser, List<Guid>> PopularList => user => PopularOrder.Where(id => !user.Seen.Contains(id)).Take(10).ToList();

        public Func<TestUser, List<Guid>> OracleList => user => Ids.Where(id => !user.Seen.Contains(id))
            .OrderByDescending(id => SyntheticTraffic.Relevance(user.Persona, ById[id], Appeal[id])).Take(10).ToList();

        public Func<TestUser, List<Guid>> Personalised(RecommendationOptions options)
        {
            if (!_neighbours.TryGetValue(options.BlendGamma, out var neighbours))
            {
                neighbours = SimilarityBlender.TopNeighbours(Ids, Ids, Content, Behaviour, options);
                _neighbours[options.BlendGamma] = neighbours;
            }

            return user => Recommender.Recommend(
                    user.Profile,
                    id => neighbours.TryGetValue(id, out var list) ? list : [],
                    Eligible,
                    user.Seen,
                    Popularity,
                    Content.Cosine,
                    10,
                    options)
                .Select(item => item.EventId)
                .ToList();
        }

        public EvaluationRow Score(string method, Func<TestUser, List<Guid>> recommend)
        {
            var sums = new double[8];
            var covered = new HashSet<Guid>();
            foreach (var user in Users)
            {
                var list = recommend(user);
                covered.UnionWith(list);
                sums[0] += Precision(list, user.Relevant, 5);
                sums[1] += Recall(list, user.Relevant, 5);
                sums[2] += Ndcg(list, user.Relevant, 5);
                sums[3] += Precision(list, user.Relevant, 10);
                sums[4] += Recall(list, user.Relevant, 10);
                sums[5] += Ndcg(list, user.Relevant, 10);
                sums[6] += list.Take(10).Any(user.Relevant.Contains) ? 1 : 0;
                sums[7] += Diversity(list);
            }

            var n = Math.Max(Users.Count, 1);
            return new EvaluationRow(method, sums[0] / n, sums[1] / n, sums[2] / n, sums[3] / n, sums[4] / n, sums[5] / n, sums[6] / n, (double)covered.Count / Ids.Count, sums[7] / n);
        }

        private double Diversity(IReadOnlyList<Guid> list)
        {
            if (list.Count < 2) return 0;
            double total = 0;
            var pairs = 0;
            for (var a = 0; a < list.Count; a++)
            {
                for (var b = a + 1; b < list.Count; b++)
                {
                    total += 1 - Content.Cosine(list[a], list[b]);
                    pairs++;
                }
            }

            return total / pairs;
        }
    }

    private static double EngagementWeight(InteractionType type) => type switch
    {
        InteractionType.DetailView => 3,
        InteractionType.Share => 4,
        InteractionType.Navigate => 5,
        _ => 0,
    };

    private static Guid NewGuid(Random random)
    {
        var bytes = new byte[16];
        random.NextBytes(bytes);
        return new Guid(bytes);
    }
}
