// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthLife.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NorthLife.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922172354_AddPublicEventQueryIndexes")]
    partial class AddPublicEventQueryIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NorthLife.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('BusinessOwner', 'Admin')");
                        });
                });

            modelBuilder.Entity("NorthLife.Api.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("end_at_utc");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_highlighted");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("locality");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("organizer_name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("StartAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue_name");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("EndAtUtc")
                        .HasDatabaseName("ix_events_end_at")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("ImageId")
                        .HasDatabaseName("ix_events_image_id");

                    b.HasIndex("OwnerId", "UpdatedAtUtc")
                        .HasDatabaseName("ix_events_owner_updated")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("IsHighlighted", "StartAtUtc", "Id")
                        .HasDatabaseName("ix_events_highlighted_start_id")
                        .HasFilter("status = 'Published' AND deleted_at_utc IS NULL");

                    b.HasIndex("Status", "StartAtUtc", "Id")
                        .HasDatabaseName("ix_events_status_start_id")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("Status", "Category", "StartAtUtc", "Id")
                        .HasDatabaseName("ix_events_status_category_start_id")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("Status", "Locality", "StartAtUtc", "Id")
                        .HasDatabaseName("ix_events_status_locality_start_id")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_category", "category IN ('Music', 'Nightlife', 'Food', 'Workshops', 'Outdoors', 'Culture', 'Sports', 'Other')");

                            t.HasCheckConstraint("ck_events_latitude", "latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_events_longitude", "longitude BETWEEN -180 AND 180");

                            t.HasCheckConstraint("ck_events_price", "price >= 0");

                            t.HasCheckConstraint("ck_events_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_events_status", "status IN ('Pending', 'Published', 'Rejected')");

                            t.HasCheckConstraint("ck_events_time_range", "end_at_utc > start_at_utc");
                        });
                });

            modelBuilder.Entity("NorthLife.Api.Models.EventImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_event_images");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_event_images_storage_key");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("ix_event_images_uploader_id");

                    b.ToTable("event_images", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_images_size", "size_bytes > 0");
                        });
                });

            modelBuilder.Entity("NorthLife.Api.Models.Event", b =>
                {
                    b.HasOne("NorthLife.Api.Models.EventImage", "Image")
                        .WithMany("Events")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_event_images_image_id");

                    b.HasOne("NorthLife.Api.Models.AppUser", "Owner")
                        .WithMany("Events")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_users_owner_id");

                    b.Navigation("Image");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NorthLife.Api.Models.EventImage", b =>
                {
                    b.HasOne("NorthLife.Api.Models.AppUser", "Uploader")
                        .WithMany("UploadedImages")
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_images_users_uploader_id");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("NorthLife.Api.Models.AppUser", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("UploadedImages");
                });

            modelBuilder.Entity("NorthLife.Api.Models.EventImage", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
